basePath: /api
definitions:
  api.LoginRequest:
    description: 用户登录请求参数
    properties:
      password:
        description: 密码
        example: password123
        type: string
      username:
        description: 用户名
        example: admin
        type: string
    type: object
  api.LoginResponse:
    description: 用户登录响应结果
    properties:
      message:
        description: 响应消息
        example: 登录成功
        type: string
      token:
        description: JWT Token
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  api.RegisterRequest:
    description: 用户注册请求参数
    properties:
      email:
        description: 邮箱
        example: newuser@example.com
        type: string
      password:
        description: 密码
        example: newpassword123
        type: string
      username:
        description: 用户名
        example: newuser
        type: string
    type: object
  api.RegisterResponse:
    description: 用户注册响应结果
    properties:
      message:
        description: 响应消息
        example: 注册成功
        type: string
      success:
        description: 是否成功
        example: true
        type: boolean
    type: object
  models.Article:
    description: 文章信息
    properties:
      authorId:
        description: 作者ID
        example: "1"
        type: string
      category:
        allOf:
        - $ref: '#/definitions/models.Category'
        description: 分类信息
      categoryId:
        description: 分类ID
        example: "1"
        type: string
      content:
        description: 文章内容
        example: 文章内容...
        type: string
      coverImage:
        description: 封面图片URL
        example: https://example.com/image.jpg
        type: string
      createdAt:
        description: 创建时间
        example: "2023-01-01T00:00:00Z"
        type: string
      excerpt:
        description: 文章摘要
        example: 文章摘要...
        type: string
      id:
        description: 文章ID
        example: "1"
        type: string
      likes:
        description: 点赞数
        example: 10
        type: integer
      published:
        description: 是否发布
        example: true
        type: boolean
      tags:
        description: 标签列表
        items:
          $ref: '#/definitions/models.Tag'
        type: array
      title:
        description: 文章标题
        example: 文章标题
        type: string
      updatedAt:
        description: 更新时间
        example: "2023-01-01T00:00:00Z"
        type: string
      views:
        description: 浏览量
        example: 100
        type: integer
    type: object
  models.Category:
    description: 文章分类信息
    properties:
      count:
        description: 文章数量
        example: 10
        type: integer
      id:
        description: 分类ID
        example: "1"
        type: string
      name:
        description: 分类名称
        example: 技术
        type: string
    type: object
  models.Tag:
    description: 文章标签信息
    properties:
      count:
        description: 文章数量
        example: 5
        type: integer
      id:
        description: 标签ID
        example: "1"
        type: string
      name:
        description: 标签名称
        example: Go
        type: string
    type: object
host: localhost:8083
info:
  contact: {}
  description: 这是一个博客系统的 API 文档
  title: 博客系统 API接口文档
  version: "1.0"
paths:
  /article:
    delete:
      description: 根据文章ID删除文章
      parameters:
      - description: 文章ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 文章ID不能为空
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 删除文章
      tags:
      - 文章
    get:
      description: 根据文章ID获取文章详情
      parameters:
      - description: 文章ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 文章详情
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 文章ID不能为空
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 文章不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取文章详情
      tags:
      - 文章
    post:
      consumes:
      - application/json
      description: 创建新文章
      parameters:
      - description: 文章信息
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/models.Article'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 标题、内容和分类不能为空
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 创建文章
      tags:
      - 文章
    put:
      consumes:
      - application/json
      description: 更新文章信息
      parameters:
      - description: 文章信息
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/models.Article'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ID、标题、内容和分类不能为空
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 更新文章
      tags:
      - 文章
  /articles:
    get:
      description: 获取所有文章的列表，支持分页
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文章列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取文章列表
      tags:
      - 文章
  /articles/category:
    get:
      description: 根据分类ID获取该分类下的文章列表，支持分页
      parameters:
      - description: 分类ID
        in: query
        name: categoryId
        required: true
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文章列表
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 分类ID不能为空
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 根据分类ID获取文章
      tags:
      - 文章
  /articles/tag:
    get:
      description: 根据标签ID获取该标签下的文章列表，支持分页
      parameters:
      - description: 标签ID
        in: query
        name: tagId
        required: true
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文章列表
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 标签ID不能为空
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 根据标签ID获取文章
      tags:
      - 文章
  /categories:
    get:
      description: 获取所有文章分类
      produces:
      - application/json
      responses:
        "200":
          description: 分类列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取分类列表
      tags:
      - 分类
  /health:
    get:
      description: 检查服务器是否正常运行
      produces:
      - application/json
      responses:
        "200":
          description: 服务器正常
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 健康检查
      tags:
      - 系统
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录接口，成功后返回JWT Token
      parameters:
      - description: 登录请求参数
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/api.LoginResponse'
        "400":
          description: 无效的请求体
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 用户名或密码错误
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - 用户认证
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册请求参数
        in: body
        name: registerReq
        required: true
        schema:
          $ref: '#/definitions/api.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功
          schema:
            $ref: '#/definitions/api.RegisterResponse'
        "400":
          description: 用户名、密码和邮箱不能为空
          schema:
            $ref: '#/definitions/api.RegisterResponse'
        "409":
          description: 用户名或邮箱已存在
          schema:
            $ref: '#/definitions/api.RegisterResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/api.RegisterResponse'
      summary: 用户注册
      tags:
      - 用户认证
  /tags:
    get:
      description: 获取所有文章标签
      produces:
      - application/json
      responses:
        "200":
          description: 标签列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取标签列表
      tags:
      - 标签
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
